# Generated by Django 5.2 on 2025-04-13 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
    ]
