# Generated by Django 5.2 on 2025-04-13 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_sintoma_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, help_text='Altura em metros', max_digits=3)),
                ('tem_diabetes', models.BooleanField(default=False)),
                ('tem_pressao_alta', models.BooleanField(default=False)),
                ('doencas_diagnosticadas', models.TextField(blank=True, help_text='Liste outras doenças já diagnosticadas')),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Paciente',
                'verbose_name_plural': 'Perfis dos Pacientes',
            },
        ),
    ]
